version: "3"

services:
  springapp:
    build: .
    container_name: playground
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://playdb:5432/playground_db
    ports:
      - 8000:8080
    expose:
      - 8080
    restart: always
    depends_on:
        - playdb
  playdb:
    image: postgres
    container_name: playdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playground_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
